/*
Nsmf_EventExposure

Session Management Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package ee

import (
	"etri5gc/sbi"
	"net/http"
)

var Routes = sbi.SbiRoutes{

	{
		Label:   "DeleteIndividualSubcription",
		Method:  http.MethodDelete,
		Path:    "/nsmf-event-exposure/v1/subscriptions/{subId}",
		Handler: OnDeleteIndividualSubcription,
	},
	{
		Label:   "GetIndividualSubcription",
		Method:  http.MethodGet,
		Path:    "/nsmf-event-exposure/v1/subscriptions/{subId}",
		Handler: OnGetIndividualSubcription,
	},
	{
		Label:   "ReplaceIndividualSubcription",
		Method:  http.MethodPut,
		Path:    "/nsmf-event-exposure/v1/subscriptions/{subId}",
		Handler: OnReplaceIndividualSubcription,
	},
	{
		Label:   "CreateIndividualSubcription",
		Method:  http.MethodPost,
		Path:    "/nsmf-event-exposure/v1/subscriptions",
		Handler: OnCreateIndividualSubcription,
	},
}
