/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package dr

import (
	"fmt"
	"net/http"
	"etri5gc/sbi"
	"etri5gc/sbi/models"
	"etri5gc/sbi/utils"
)


/*
@param client sbi.ConsumerClient - for encoding request/encoding response and sending request to remote agent.
@param influenceIds Each element identifies a service.
@param dnns Each element identifies a DNN.
@param snssais Each element identifies a slice.
@param internalGroupIds Each element identifies a group of users.
@param supis Each element identifies the user.
@param suppFeat Supported Features
@return []models.TrafficInfluData, 
*/
func ReadInfluenceData(client sbi.ConsumerClient, influenceIds []string, dnns []string, snssais []models.Snssai, internalGroupIds []string, supis []string, suppFeat string) (result []models.TrafficInfluData, err error) {
						
	//create a request
	req := sbi.DefaultRequest()
	req.Method = http.MethodGet

	req.Path = fmt.Sprintf("%s/application-data/influenceData", ServicePath)
	influenceIdsStr := utils.Param2String(influenceIds)
	if len(influenceIdsStr) > 0 {
		req.QueryParams.Add("influence-Ids", influenceIdsStr)
	}
	dnnsStr := utils.Param2String(dnns)
	if len(dnnsStr) > 0 {
		req.QueryParams.Add("dnns", dnnsStr)
	}
	snssaisStr := utils.Param2String(snssais)
	if len(snssaisStr) > 0 {
		req.QueryParams.Add("snssais", snssaisStr)
	}
	internalGroupIdsStr := utils.Param2String(internalGroupIds)
	if len(internalGroupIdsStr) > 0 {
		req.QueryParams.Add("internal-Group-Ids", internalGroupIdsStr)
	}
	supisStr := utils.Param2String(supis)
	if len(supisStr) > 0 {
		req.QueryParams.Add("supis", supisStr)
	}
	if len(suppFeat) > 0 {
		req.QueryParams.Add("supp-feat", suppFeat)
	}	
	req.HeaderParams["Accept"] = "application/json, application/problem+json"
	//send the request
	var resp *sbi.Response
	if resp, err = client.Send(req); err != nil {
		return
	}

	//handle the response
	if resp.StatusCode >= 300 {
		if resp.StatusCode == 400 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 401 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 403 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 404 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 414 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 429 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 500 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 503 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.Body != nil {
			if err = client.DecodeResponse(resp); err == nil {
				err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
			}
			return
		} else {
			err = fmt.Errorf("%d is unknown to ReadInfluenceData", resp.StatusCode)
			return
		}
	}

	resp.Body = &result
	if err = client.DecodeResponse(resp); err == nil {
		err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
	}
	return 
}


//sbi producer handler for ReadInfluenceData
func OnReadInfluenceData(ctx sbi.RequestContext, handler interface{}) (resp sbi.Response) {
	prod := handler.(InfluenceDataStoreApiHandler)
	
	influenceIdsStr := ctx.Param("influence-Ids")
	var influenceIds []string
	var influenceIdsErr error
	if influenceIds, influenceIdsErr = utils.String2ArrayOfstring(influenceIdsStr); influenceIdsErr != nil {
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: influenceIdsErr.Error(), 
		}))
		return
	}
	
	dnnsStr := ctx.Param("dnns")
	var dnns []string
	var dnnsErr error
	if dnns, dnnsErr = utils.String2ArrayOfstring(dnnsStr); dnnsErr != nil {
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: dnnsErr.Error(), 
		}))
		return
	}
	
	snssaisStr := ctx.Param("snssais")
	var snssais []models.Snssai
	var snssaisErr error
	if snssais, snssaisErr = utils.String2ArrayOfSnssai(snssaisStr); snssaisErr != nil {
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: snssaisErr.Error(), 
		}))
		return
	}
	
	internalGroupIdsStr := ctx.Param("internal-Group-Ids")
	var internalGroupIds []string
	var internalGroupIdsErr error
	if internalGroupIds, internalGroupIdsErr = utils.String2ArrayOfstring(internalGroupIdsStr); internalGroupIdsErr != nil {
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: internalGroupIdsErr.Error(), 
		}))
		return
	}
	
	supisStr := ctx.Param("supis")
	var supis []string
	var supisErr error
	if supis, supisErr = utils.String2ArrayOfstring(supisStr); supisErr != nil {
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: supisErr.Error(), 
		}))
		return
	}
	
	suppFeat := ctx.Param("supp-feat")

	

	var apierr *sbi.ApiError
	var successCode int32
	var result []models.TrafficInfluData


	successCode, result, apierr = prod.DR_HandleReadInfluenceData(influenceIds, dnns, snssais, internalGroupIds, supis, suppFeat)

	if apierr != nil {
		resp.SetApiError(apierr)
	} else {
		resp.SetBody(int(successCode), &result)
	}
	return
}




type InfluenceDataStoreApiHandler interface {
	DR_HandleReadInfluenceData(influenceIds []string, dnns []string, snssais []models.Snssai, internalGroupIds []string, supis []string, suppFeat string) (successCode int32, result []models.TrafficInfluData, err *sbi.ApiError)
}
