/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package dr

import (
	"fmt"
	"net/http"
	"net/url"
	"etri5gc/sbi"
	"etri5gc/sbi/models"
	"strings"
)


/*
@param client sbi.ConsumerClient - for encoding request/encoding response and sending request to remote agent.
@param ueGroupId Group of UEs or any UE
@return *models.EeSubscription, 
*/
func CreateEeGroupSubscriptions(client sbi.ConsumerClient, ueGroupId string, body models.EeSubscription) (result models.EeSubscription, err error) {
	
	if len(ueGroupId) == 0 {
		err = fmt.Errorf("ueGroupId is required")
		return
	}	
	//create a request
	req := sbi.DefaultRequest()
	req.Method = http.MethodPost

	req.Path = fmt.Sprintf("%s/subscription-data/group-data/{ueGroupId}/ee-subscriptions", ServicePath)
	req.Path = strings.Replace(req.Path, "{"+"ueGroupId"+"}", url.PathEscape(ueGroupId), -1)
	req.Body = &body
	req.HeaderParams["Content-Type"] = "application/json"
	req.HeaderParams["Accept"] = "application/json"
	//send the request
	var resp *sbi.Response
	if resp, err = client.Send(req); err != nil {
		return
	}

	//handle the response
	if resp.StatusCode >= 300 {
		if resp.Body != nil {
			if err = client.DecodeResponse(resp); err == nil {
				err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
			}
			return
		} else {
			err = fmt.Errorf("%d is unknown to CreateEeGroupSubscriptions", resp.StatusCode)
			return
		}
	}

	resp.Body = &result
	if err = client.DecodeResponse(resp); err == nil {
		err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
	}
	return 
}


//sbi producer handler for CreateEeGroupSubscriptions
func OnCreateEeGroupSubscriptions(ctx sbi.RequestContext, handler interface{}) (resp sbi.Response) {
	prod := handler.(EventExposureGroupSubscriptionsCollectionApiHandler)
	
	ueGroupId := ctx.Param("ueGroupId")
	if len(ueGroupId) == 0 {
		//ueGroupId is required
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: "ueGroupId is required",
		}))
		return
	}

	var input models.EeSubscription

	var apierr *sbi.ApiError
	var successCode int32
	var result models.EeSubscription

	if prob := ctx.DecodeRequest(&input); prob == nil {
		successCode, result, apierr = prod.DR_HandleCreateEeGroupSubscriptions(ueGroupId, input)
	} else {
		apierr = sbi.ApiErrFromProb(prob)
	}
	

	if apierr != nil {
		resp.SetApiError(apierr)
	} else {
		resp.SetBody(int(successCode), &result)
	}
	return
}




/*
@param client sbi.ConsumerClient - for encoding request/encoding response and sending request to remote agent.
@param ueGroupId Group of UEs or any UE
@param supportedFeatures Supported Features
@return []models.EeSubscription, 
*/
func QueryEeGroupSubscriptions(client sbi.ConsumerClient, ueGroupId string, supportedFeatures string) (result []models.EeSubscription, err error) {
	
	if len(ueGroupId) == 0 {
		err = fmt.Errorf("ueGroupId is required")
		return
	}	
	//create a request
	req := sbi.DefaultRequest()
	req.Method = http.MethodGet

	req.Path = fmt.Sprintf("%s/subscription-data/group-data/{ueGroupId}/ee-subscriptions", ServicePath)
	req.Path = strings.Replace(req.Path, "{"+"ueGroupId"+"}", url.PathEscape(ueGroupId), -1)
	if len(supportedFeatures) > 0 {
		req.QueryParams.Add("supported-features", supportedFeatures)
	}	
	req.HeaderParams["Accept"] = "application/json"
	//send the request
	var resp *sbi.Response
	if resp, err = client.Send(req); err != nil {
		return
	}

	//handle the response
	if resp.StatusCode >= 300 {
		if resp.Body != nil {
			if err = client.DecodeResponse(resp); err == nil {
				err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
			}
			return
		} else {
			err = fmt.Errorf("%d is unknown to QueryEeGroupSubscriptions", resp.StatusCode)
			return
		}
	}

	resp.Body = &result
	if err = client.DecodeResponse(resp); err == nil {
		err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
	}
	return 
}


//sbi producer handler for QueryEeGroupSubscriptions
func OnQueryEeGroupSubscriptions(ctx sbi.RequestContext, handler interface{}) (resp sbi.Response) {
	prod := handler.(EventExposureGroupSubscriptionsCollectionApiHandler)
	
	ueGroupId := ctx.Param("ueGroupId")
	if len(ueGroupId) == 0 {
		//ueGroupId is required
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: "ueGroupId is required",
		}))
		return
	}
	supportedFeatures := ctx.Param("supported-features")

	

	var apierr *sbi.ApiError
	var successCode int32
	var result []models.EeSubscription


	successCode, result, apierr = prod.DR_HandleQueryEeGroupSubscriptions(ueGroupId, supportedFeatures)

	if apierr != nil {
		resp.SetApiError(apierr)
	} else {
		resp.SetBody(int(successCode), &result)
	}
	return
}




type EventExposureGroupSubscriptionsCollectionApiHandler interface {
	DR_HandleCreateEeGroupSubscriptions(ueGroupId string, body models.EeSubscription) (successCode int32, result models.EeSubscription, err *sbi.ApiError)
	DR_HandleQueryEeGroupSubscriptions(ueGroupId string, supportedFeatures string) (successCode int32, result []models.EeSubscription, err *sbi.ApiError)
}
