/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package dr

import (
	"fmt"
	"net/http"
	"net/url"
	"etri5gc/sbi"
	"etri5gc/sbi/models"
	"strings"
)


/*
@param client sbi.ConsumerClient - for encoding request/encoding response and sending request to remote agent.
@param externalGroupId
@return *models.Model5GVnGroupConfiguration, 
*/
func Create5GVnGroup(client sbi.ConsumerClient, externalGroupId string, body models.Model5GVnGroupConfiguration) (result models.Model5GVnGroupConfiguration, err error) {
	
	if len(externalGroupId) == 0 {
		err = fmt.Errorf("externalGroupId is required")
		return
	}	
	//create a request
	req := sbi.DefaultRequest()
	req.Method = http.MethodPut

	req.Path = fmt.Sprintf("%s/subscription-data/group-data/5g-vn-groups/{externalGroupId}", ServicePath)
	req.Path = strings.Replace(req.Path, "{"+"externalGroupId"+"}", url.PathEscape(externalGroupId), -1)
	req.Body = &body
	req.HeaderParams["Content-Type"] = "application/json"
	req.HeaderParams["Accept"] = "application/json, application/problem+json"
	//send the request
	var resp *sbi.Response
	if resp, err = client.Send(req); err != nil {
		return
	}

	//handle the response
	if resp.StatusCode >= 300 {
		if resp.StatusCode == 403 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.Body != nil {
			if err = client.DecodeResponse(resp); err == nil {
				err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
			}
			return
		} else {
			err = fmt.Errorf("%d is unknown to Create5GVnGroup", resp.StatusCode)
			return
		}
	}

	resp.Body = &result
	if err = client.DecodeResponse(resp); err == nil {
		err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
	}
	return 
}


//sbi producer handler for Create5GVnGroup
func OnCreate5GVnGroup(ctx sbi.RequestContext, handler interface{}) (resp sbi.Response) {
	prod := handler.(Class5GVnGroupConfigurationDocumentApiHandler)
	
	externalGroupId := ctx.Param("externalGroupId")
	if len(externalGroupId) == 0 {
		//externalGroupId is required
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: "externalGroupId is required",
		}))
		return
	}

	var input models.Model5GVnGroupConfiguration

	var apierr *sbi.ApiError
	var successCode int32
	var result models.Model5GVnGroupConfiguration

	if prob := ctx.DecodeRequest(&input); prob == nil {
		successCode, result, apierr = prod.DR_HandleCreate5GVnGroup(externalGroupId, input)
	} else {
		apierr = sbi.ApiErrFromProb(prob)
	}
	

	if apierr != nil {
		resp.SetApiError(apierr)
	} else {
		resp.SetBody(int(successCode), &result)
	}
	return
}




type Class5GVnGroupConfigurationDocumentApiHandler interface {
	DR_HandleCreate5GVnGroup(externalGroupId string, body models.Model5GVnGroupConfiguration) (successCode int32, result models.Model5GVnGroupConfiguration, err *sbi.ApiError)
}
