/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package comm

import (
	"fmt"
	"net/http"
	"net/url"
	"etri5gc/sbi"
	"etri5gc/sbi/models"
	"strings"
)


/*
@param client sbi.ConsumerClient - for encoding request/encoding response and sending request to remote agent.
@param n2NotifySubscriptionId N2 info Subscription Identifier
@return 
*/
func NonUeN2InfoUnSubscribe(client sbi.ConsumerClient, n2NotifySubscriptionId string) (err error) {
	
	if len(n2NotifySubscriptionId) == 0 {
		err = fmt.Errorf("n2NotifySubscriptionId is required")
		return
	}
	//create a request
	req := sbi.DefaultRequest()
	req.Method = http.MethodDelete

	req.Path = fmt.Sprintf("%s/non-ue-n2-messages/subscriptions/{n2NotifySubscriptionId}", ServicePath)
	req.Path = strings.Replace(req.Path, "{"+"n2NotifySubscriptionId"+"}", url.PathEscape(n2NotifySubscriptionId), -1)	
	req.HeaderParams["Accept"] = "application/json, application/problem+json"
	//send the request
	var resp *sbi.Response
	if resp, err = client.Send(req); err != nil {
		return
	}

	//handle the response
	if resp.StatusCode >= 300 {
		if resp.StatusCode == 307 {
			resp.Body = &models.RedirectResponse{}
		}
		if resp.StatusCode == 308 {
			resp.Body = &models.RedirectResponse{}
		}
		if resp.StatusCode == 400 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 429 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 500 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.StatusCode == 503 {
			resp.Body = &models.ProblemDetails{}
		}
		if resp.Body != nil {
			if err = client.DecodeResponse(resp); err == nil {
				err = sbi.NewApiError(resp.StatusCode, resp.Status, resp.Body)	
			}
			return
		} else {
			err = fmt.Errorf("%d is unknown to NonUeN2InfoUnSubscribe", resp.StatusCode)
			return
		}
	}

	return 
}


//sbi producer handler for NonUeN2InfoUnSubscribe
func OnNonUeN2InfoUnSubscribe(ctx sbi.RequestContext, handler interface{}) (resp sbi.Response) {
	prod := handler.(NonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler)
	
	n2NotifySubscriptionId := ctx.Param("n2NotifySubscriptionId")
	if len(n2NotifySubscriptionId) == 0 {
		//n2NotifySubscriptionId is required
		resp.SetApiError(sbi.ApiErrFromProb(&models.ProblemDetails{
			Title: "Bad request",
			Status: http.StatusBadRequest,
			Detail: "n2NotifySubscriptionId is required",
		}))
		return
	}

	

	var apierr *sbi.ApiError
	var successCode int32

	successCode, apierr = prod.COMM_HandleNonUeN2InfoUnSubscribe(n2NotifySubscriptionId)

	if apierr != nil {
		resp.SetApiError(apierr)
	} else {
		resp.SetBody(int(successCode), nil)
	}
	return
}




type NonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler interface {
	COMM_HandleNonUeN2InfoUnSubscribe(n2NotifySubscriptionId string) (successCode int32, err *sbi.ApiError)
}
