/*
Nsmf_PDUSession

SMF PDU Session Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package pdu

import (
	"etrib5gc/sbi"
	"net/http"
)

var Routes = sbi.SbiRoutes{

	{
		Label:   "ReleasePduSession",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/pdu-sessions/{pduSessionRef}/release",
		Handler: OnReleasePduSession,
	},
	{
		Label:   "RetrievePduSession",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/pdu-sessions/{pduSessionRef}/retrieve",
		Handler: OnRetrievePduSession,
	},
	{
		Label:   "TransferMoData",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/pdu-sessions/{pduSessionRef}/transfer-mo-data",
		Handler: OnTransferMoData,
	},
	{
		Label:   "UpdatePduSession",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/pdu-sessions/{pduSessionRef}/modify",
		Handler: OnUpdatePduSession,
	},
	{
		Label:   "ReleaseSmContext",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/sm-contexts/{smContextRef}/release",
		Handler: OnReleaseSmContext,
	},
	{
		Label:   "RetrieveSmContext",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/sm-contexts/{smContextRef}/retrieve",
		Handler: OnRetrieveSmContext,
	},
	{
		Label:   "SendMoData",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/sm-contexts/{smContextRef}/send-mo-data",
		Handler: OnSendMoData,
	},
	{
		Label:   "UpdateSmContext",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/sm-contexts/{smContextRef}/modify",
		Handler: OnUpdateSmContext,
	},
	{
		Label:   "PostPduSessions",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/pdu-sessions",
		Handler: OnPostPduSessions,
	},
	{
		Label:   "PostSmContexts",
		Method:  http.MethodPost,
		Path:    "/nsmf-pdusession/v1/sm-contexts",
		Handler: OnPostSmContexts,
	},
}
