/*
AUSF API

AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package uea

import (
	"etrib5gc/sbi"
	"net/http"
)

var Routes = sbi.SbiRoutes{

	{
		Label:   "Delete5gAkaAuthenticationResult",
		Method:  http.MethodDelete,
		Path:    "/nausf-auth/v1/ue-authentications/{authCtxId}/5g-aka-confirmation",
		Handler: OnDelete5gAkaAuthenticationResult,
	},
	{
		Label:   "DeleteEapAuthenticationResult",
		Method:  http.MethodDelete,
		Path:    "/nausf-auth/v1/ue-authentications/{authCtxId}/eap-session",
		Handler: OnDeleteEapAuthenticationResult,
	},
	{
		Label:   "EapAuthMethod",
		Method:  http.MethodPost,
		Path:    "/nausf-auth/v1/ue-authentications/{authCtxId}/eap-session",
		Handler: OnEapAuthMethod,
	},
	{
		Label:   "RgAuthenticationsPost",
		Method:  http.MethodPost,
		Path:    "/nausf-auth/v1/rg-authentications",
		Handler: OnRgAuthenticationsPost,
	},
	{
		Label:   "UeAuthenticationsAuthCtxId5gAkaConfirmationPut",
		Method:  http.MethodPut,
		Path:    "/nausf-auth/v1/ue-authentications/{authCtxId}/5g-aka-confirmation",
		Handler: OnUeAuthenticationsAuthCtxId5gAkaConfirmationPut,
	},
	{
		Label:   "UeAuthenticationsDeregisterPost",
		Method:  http.MethodPost,
		Path:    "/nausf-auth/v1/ue-authentications/deregister",
		Handler: OnUeAuthenticationsDeregisterPost,
	},
	{
		Label:   "UeAuthenticationsPost",
		Method:  http.MethodPost,
		Path:    "/nausf-auth/v1/ue-authentications",
		Handler: OnUeAuthenticationsPost,
	},
}
