/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package location

import (
	"strings"

	"etri5gc/nfs/amf/sbi/producer"
	"etri5gc/sbi"
)

const (
	SERVICE_NAME="/namf-loc/v1"
)

type Handler struct {
	prod		*producer.Handler
}

func MakeRoutes(p *producer.Handler) (string, sbi.Routes) {
	h := &Handler{
		prod:	p,
	}
	var routes = sbi.Routes{
		{
			"Index",
			"GET",
			"/",
			sbi.IndexHandler,
		},

		{
			"ProvideLocationInfo",
			strings.ToUpper("Post"),
			"/:ueContextId/provide-loc-info",
			h.HTTPProvideLocationInfo,
		},

		{
			"ProvidePositioningInfo",
			strings.ToUpper("Post"),
			"/:ueContextId/provide-pos-info",
			h.HTTPProvidePositioningInfo,
		},
	}
	return SERVICE_NAME, routes
}	
