/*
Nausf_SoRProtection Service

AUSF SoR Protection Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type SorSecurityInfo struct {
	SorMacIausf string `json:"sorMacIausf"`

	CounterSor string `json:"counterSor"`

	SorXmacIue string `json:"sorXmacIue,omitempty"`
}
