/*
Namf_EventExposure

AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ReachabilityFilter string

// List of ReachabilityFilter
const (
	REACHABILITYFILTER_REACHABILITY_STATUS_CHANGE ReachabilityFilter = "UE_REACHABILITY_STATUS_CHANGE"
	REACHABILITYFILTER_REACHABLE_DL_TRAFFIC       ReachabilityFilter = "UE_REACHABLE_DL_TRAFFIC"
)
