/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type PresenceInfo struct {
	PraId string `json:"praId,omitempty"`

	AdditionalPraId string `json:"additionalPraId,omitempty"`

	PresenceState PresenceState `json:"presenceState,omitempty"`

	TrackingAreaList []Tai `json:"trackingAreaList,omitempty"`

	EcgiList []Ecgi `json:"ecgiList,omitempty"`

	NcgiList []Ncgi `json:"ncgiList,omitempty"`

	GlobalRanNodeIdList []GlobalRanNodeId `json:"globalRanNodeIdList,omitempty"`

	GlobaleNbIdList []GlobalRanNodeId `json:"globaleNbIdList,omitempty"`
}
