/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type SmPolicyContextData struct {
	AccNetChId AccNetChId `json:"accNetChId,omitempty"`

	ChargEntityAddr AccNetChargingAddress `json:"chargEntityAddr,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	Supi string `json:"supi"`

	// When this attribute is included and set to true, it indicates that the supi attribute contains an invalid value.This attribute shall be present if the SUPI is not available in the SMF or the SUPI is unauthenticated. When present it shall be set to true for an invalid SUPI and false (default) for a valid SUPI.
	InvalidSupi bool `json:"invalidSupi,omitempty"`

	InterGrpIds []string `json:"interGrpIds,omitempty"`

	PduSessionId int32 `json:"pduSessionId"`

	PduSessionType PduSessionType `json:"pduSessionType"`

	Chargingcharacteristics string `json:"chargingcharacteristics,omitempty"`

	Dnn string `json:"dnn"`

	DnnSelMode DnnSelectionMode `json:"dnnSelMode,omitempty"`

	NotificationUri string `json:"notificationUri"`

	AccessType AccessType `json:"accessType,omitempty"`

	RatType RatType `json:"ratType,omitempty"`

	AddAccessInfo AdditionalAccessInfo `json:"addAccessInfo,omitempty"`

	ServingNetwork PlmnIdNid `json:"servingNetwork,omitempty"`

	UserLocationInfo UserLocation `json:"userLocationInfo,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`

	Pei string `json:"pei,omitempty"`

	Ipv4Address string `json:"ipv4Address,omitempty"`

	Ipv6AddressPrefix Ipv6Prefix `json:"ipv6AddressPrefix,omitempty"`

	// Indicates the IPv4 address domain
	IpDomain string `json:"ipDomain,omitempty"`

	SubsSessAmbr Ambr `json:"subsSessAmbr,omitempty"`

	// Indicates the DN-AAA authorization profile index
	AuthProfIndex string `json:"authProfIndex,omitempty"`

	SubsDefQos SubscribedDefaultQos `json:"subsDefQos,omitempty"`

	VplmnQos VplmnQos `json:"vplmnQos,omitempty"`

	// Contains the number of supported packet filter for signalled QoS rules.
	NumOfPackFilter int32 `json:"numOfPackFilter,omitempty"`

	// If it is included and set to true, the online charging is applied to the PDU session.
	Online bool `json:"online,omitempty"`

	// If it is included and set to true, the offline charging is applied to the PDU session.
	Offline bool `json:"offline,omitempty"`

	// If it is included and set to true, the 3GPP PS Data Off is activated by the UE.
	Var3gppPsDataOffStatus bool `json:"3gppPsDataOffStatus,omitempty"`

	// If it is included and set to true, the reflective QoS is supported by the UE.
	RefQosIndication bool `json:"refQosIndication,omitempty"`

	TraceReq *TraceData `json:"traceReq,omitempty"`

	SliceInfo Snssai `json:"sliceInfo"`

	QosFlowUsage QosFlowUsage `json:"qosFlowUsage,omitempty"`

	ServNfId ServingNfIdentity `json:"servNfId,omitempty"`

	SuppFeat string `json:"suppFeat,omitempty"`

	SmfId string `json:"smfId,omitempty"`

	RecoveryTime time.Time `json:"recoveryTime,omitempty"`

	MaPduInd MaPduIndication `json:"maPduInd,omitempty"`

	AtsssCapab AtsssCapability `json:"atsssCapab,omitempty"`

	Ipv4FrameRouteList []string `json:"ipv4FrameRouteList,omitempty"`

	Ipv6FrameRouteList []Ipv6Prefix `json:"ipv6FrameRouteList,omitempty"`
}
