/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type AuthEvent struct {
	NfInstanceId string `json:"nfInstanceId"`

	Success bool `json:"success"`

	TimeStamp time.Time `json:"timeStamp"`

	AuthType AuthType `json:"authType"`

	ServingNetworkName string `json:"servingNetworkName"`

	AuthRemovalInd bool `json:"authRemovalInd,omitempty"`

	NfSetId string `json:"nfSetId,omitempty"`
}
