/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ReportingAreaType string

// List of ReportingAreaType
const (
	REPORTINGAREATYPE_EPS_TRACKING_AREA_IDENTITY         ReportingAreaType = "EPS_TRACKING_AREA_IDENTITY"
	REPORTINGAREATYPE_E_UTRAN_CELL_GLOBAL_IDENTIFICATION ReportingAreaType = "E-UTRAN_CELL_GLOBAL_IDENTIFICATION"
	REPORTINGAREATYPE__5_GS_TRACKING_AREA_IDENTITY       ReportingAreaType = "5GS_TRACKING_AREA_IDENTITY"
	REPORTINGAREATYPE_NR_CELL_GLOBAL_IDENTITY            ReportingAreaType = "NR_CELL_GLOBAL_IDENTITY"
)
