/*
Npcf_EventExposure

PCF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type PcEventExposureSubsc struct {
	EventSubs []PcEvent `json:"eventSubs"`

	EventsRepInfo ReportingInformation `json:"eventsRepInfo,omitempty"`

	GroupId string `json:"groupId,omitempty"`

	FilterDnns []string `json:"filterDnns,omitempty"`

	FilterSnssais []Snssai `json:"filterSnssais,omitempty"`

	FilterServices []ServiceIdentification `json:"filterServices,omitempty"`

	NotifUri string `json:"notifUri"`

	NotifId string `json:"notifId"`

	SuppFeat string `json:"suppFeat,omitempty"`
}
