/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

// TemporalValidity - Indicates the time interval(s) during which the AF request is to be applied
type TemporalValidity struct {
	StartTime time.Time `json:"startTime,omitempty"`

	StopTime time.Time `json:"stopTime,omitempty"`
}
