/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ReportingAreaTypeAnyOf string

// List of ReportingAreaTypeAnyOf
const (
	REPORTINGAREATYPEANYOF_EPS_TRACKING_AREA_IDENTITY         ReportingAreaTypeAnyOf = "EPS_TRACKING_AREA_IDENTITY"
	REPORTINGAREATYPEANYOF_E_UTRAN_CELL_GLOBAL_IDENTIFICATION ReportingAreaTypeAnyOf = "E-UTRAN_CELL_GLOBAL_IDENTIFICATION"
	REPORTINGAREATYPEANYOF__5_GS_TRACKING_AREA_IDENTITY       ReportingAreaTypeAnyOf = "5GS_TRACKING_AREA_IDENTITY"
	REPORTINGAREATYPEANYOF_NR_CELL_GLOBAL_IDENTITY            ReportingAreaTypeAnyOf = "NR_CELL_GLOBAL_IDENTITY"
)
