/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type SmsSupport string

// List of SmsSupport
const (
	SMSSUPPORTANYOF__3_GPP    SmsSupport = "3GPP"
	SMSSUPPORTANYOF_NON_3_GPP SmsSupport = "NON_3GPP"
	SMSSUPPORTANYOF_BOTH      SmsSupport = "BOTH"
	SMSSUPPORTANYOF_NONE      SmsSupport = "NONE"
)
