/*
Nudm_MT

UDM MT Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type B5GsUserState string

// List of 5GsUserState
const (
	B5GSUSERSTATEANYOF_DEREGISTERED                       B5GsUserState = "DEREGISTERED"
	B5GSUSERSTATEANYOF_CONNECTED_NOT_REACHABLE_FOR_PAGING B5GsUserState = "CONNECTED_NOT_REACHABLE_FOR_PAGING"
	B5GSUSERSTATEANYOF_CONNECTED_REACHABLE_FOR_PAGING     B5GsUserState = "CONNECTED_REACHABLE_FOR_PAGING"
	B5GSUSERSTATEANYOF_NOT_PROVIDED_FROM_AMF              B5GsUserState = "NOT_PROVIDED_FROM_AMF"
)
