/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type SmPolicyAssociationReleaseCause string

// List of SmPolicyAssociationReleaseCause
const (
	SMPOLICYASSOCIATIONRELEASECAUSE_UNSPECIFIED                  SmPolicyAssociationReleaseCause = "UNSPECIFIED"
	SMPOLICYASSOCIATIONRELEASECAUSE_UE_SUBSCRIPTION              SmPolicyAssociationReleaseCause = "UE_SUBSCRIPTION"
	SMPOLICYASSOCIATIONRELEASECAUSE_INSUFFICIENT_RES             SmPolicyAssociationReleaseCause = "INSUFFICIENT_RES"
	SMPOLICYASSOCIATIONRELEASECAUSE_VALIDATION_CONDITION_NOT_MET SmPolicyAssociationReleaseCause = "VALIDATION_CONDITION_NOT_MET"
)
