/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type LoggingIntervalNrMdtAnyOf string

// List of LoggingIntervalNrMdtAnyOf
const (
	LOGGINGINTERVALNRMDTANYOF__128     LoggingIntervalNrMdtAnyOf = "128"
	LOGGINGINTERVALNRMDTANYOF__256     LoggingIntervalNrMdtAnyOf = "256"
	LOGGINGINTERVALNRMDTANYOF__512     LoggingIntervalNrMdtAnyOf = "512"
	LOGGINGINTERVALNRMDTANYOF__1024    LoggingIntervalNrMdtAnyOf = "1024"
	LOGGINGINTERVALNRMDTANYOF__2048    LoggingIntervalNrMdtAnyOf = "2048"
	LOGGINGINTERVALNRMDTANYOF__3072    LoggingIntervalNrMdtAnyOf = "3072"
	LOGGINGINTERVALNRMDTANYOF__4096    LoggingIntervalNrMdtAnyOf = "4096"
	LOGGINGINTERVALNRMDTANYOF__6144    LoggingIntervalNrMdtAnyOf = "6144"
	LOGGINGINTERVALNRMDTANYOF__320     LoggingIntervalNrMdtAnyOf = "320"
	LOGGINGINTERVALNRMDTANYOF__640     LoggingIntervalNrMdtAnyOf = "640"
	LOGGINGINTERVALNRMDTANYOF_INFINITY LoggingIntervalNrMdtAnyOf = "infinity"
)
