/*
Nsmf_PDUSession

SMF PDU Session Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ResourceStatusAnyOf string

// List of ResourceStatusAnyOf
const (
	RESOURCESTATUSANYOF_RELEASED ResourceStatusAnyOf = "RELEASED"
	RESOURCESTATUSANYOF_UNCHANGED ResourceStatusAnyOf = "UNCHANGED"
	RESOURCESTATUSANYOF_TRANSFERRED ResourceStatusAnyOf = "TRANSFERRED"
	RESOURCESTATUSANYOF_UPDATED ResourceStatusAnyOf = "UPDATED"
	RESOURCESTATUSANYOF_ALT_ANCHOR_SMF ResourceStatusAnyOf = "ALT_ANCHOR_SMF"
)
