/*
Nsmf_PDUSession

SMF PDU Session Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RequestIndication string

// List of RequestIndication
const (
	REQUESTINDICATION_UE_REQ_PDU_SES_MOD        RequestIndication = "UE_REQ_PDU_SES_MOD"
	REQUESTINDICATION_UE_REQ_PDU_SES_REL        RequestIndication = "UE_REQ_PDU_SES_REL"
	REQUESTINDICATION_PDU_SES_MOB               RequestIndication = "PDU_SES_MOB"
	REQUESTINDICATION_NW_REQ_PDU_SES_AUTH       RequestIndication = "NW_REQ_PDU_SES_AUTH"
	REQUESTINDICATION_NW_REQ_PDU_SES_MOD        RequestIndication = "NW_REQ_PDU_SES_MOD"
	REQUESTINDICATION_NW_REQ_PDU_SES_REL        RequestIndication = "NW_REQ_PDU_SES_REL"
	REQUESTINDICATION_EBI_ASSIGNMENT_REQ        RequestIndication = "EBI_ASSIGNMENT_REQ"
	REQUESTINDICATION_REL_DUE_TO_5_G_AN_REQUEST RequestIndication = "REL_DUE_TO_5G_AN_REQUEST"
)
