/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type SensorMeasurementAnyOf string

// List of SensorMeasurementAnyOf
const (
	SENSORMEASUREMENTANYOF_BAROMETRIC_PRESSURE SensorMeasurementAnyOf = "BAROMETRIC_PRESSURE"
	SENSORMEASUREMENTANYOF_UE_SPEED SensorMeasurementAnyOf = "UE_SPEED"
	SENSORMEASUREMENTANYOF_UE_ORIENTATION SensorMeasurementAnyOf = "UE_ORIENTATION"
)
