/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type SdmSubscription1 struct {

	NfInstanceId string `json:"nfInstanceId"`

	ImplicitUnsubscribe bool `json:"implicitUnsubscribe,omitempty"`

	Expires time.Time `json:"expires,omitempty"`

	CallbackReference string `json:"callbackReference"`

	AmfServiceName ServiceName `json:"amfServiceName,omitempty"`

	MonitoredResourceUris []string `json:"monitoredResourceUris"`

	SingleNssai Snssai `json:"singleNssai,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	SubscriptionId string `json:"subscriptionId,omitempty"`

	PlmnId PlmnId1 `json:"plmnId,omitempty"`

	ImmediateReport bool `json:"immediateReport,omitempty"`

	Report SubscriptionDataSets1 `json:"report,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	ContextInfo ContextInfo `json:"contextInfo,omitempty"`

	UniqueSubscription bool `json:"uniqueSubscription,omitempty"`
}
