/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RatType string

// List of RatType
const (
	RATTYPE_NR             RatType = "NR"
	RATTYPE_EUTRA          RatType = "EUTRA"
	RATTYPE_WLAN           RatType = "WLAN"
	RATTYPE_VIRTUAL        RatType = "VIRTUAL"
	RATTYPE_NBIOT          RatType = "NBIOT"
	RATTYPE_WIRELINE       RatType = "WIRELINE"
	RATTYPE_WIRELINE_CABLE RatType = "WIRELINE_CABLE"
	RATTYPE_WIRELINE_BBF   RatType = "WIRELINE_BBF"
	RATTYPE_LTE_M          RatType = "LTE-M"
	RATTYPE_NR_U           RatType = "NR_U"
	RATTYPE_EUTRA_U        RatType = "EUTRA_U"
	RATTYPE_TRUSTED_N3_GA  RatType = "TRUSTED_N3GA"
	RATTYPE_TRUSTED_WLAN   RatType = "TRUSTED_WLAN"
	RATTYPE_UTRA           RatType = "UTRA"
	RATTYPE_GERA           RatType = "GERA"
)
