/*
Npcf_UEPolicyControl

UE Policy Control Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type Pc5Capability string

// List of Pc5Capability
const (
	PC5CAPABILITY_LTE_PC5    Pc5Capability = "LTE_PC5"
	PC5CAPABILITY_NR_PC5     Pc5Capability = "NR_PC5"
	PC5CAPABILITY_LTE_NR_PC5 Pc5Capability = "LTE_NR_PC5"
)
