/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type AfEvent string

// List of AfEvent
const (
	AFEVENT_ACCESS_TYPE_CHANGE              AfEvent = "ACCESS_TYPE_CHANGE"
	AFEVENT_ANI_REPORT                      AfEvent = "ANI_REPORT"
	AFEVENT_CHARGING_CORRELATION            AfEvent = "CHARGING_CORRELATION"
	AFEVENT_EPS_FALLBACK                    AfEvent = "EPS_FALLBACK"
	AFEVENT_FAILED_RESOURCES_ALLOCATION     AfEvent = "FAILED_RESOURCES_ALLOCATION"
	AFEVENT_OUT_OF_CREDIT                   AfEvent = "OUT_OF_CREDIT"
	AFEVENT_PLMN_CHG                        AfEvent = "PLMN_CHG"
	AFEVENT_QOS_MONITORING                  AfEvent = "QOS_MONITORING"
	AFEVENT_QOS_NOTIF                       AfEvent = "QOS_NOTIF"
	AFEVENT_RAN_NAS_CAUSE                   AfEvent = "RAN_NAS_CAUSE"
	AFEVENT_REALLOCATION_OF_CREDIT          AfEvent = "REALLOCATION_OF_CREDIT"
	AFEVENT_SUCCESSFUL_RESOURCES_ALLOCATION AfEvent = "SUCCESSFUL_RESOURCES_ALLOCATION"
	AFEVENT_TSN_BRIDGE_INFO                 AfEvent = "TSN_BRIDGE_INFO"
	AFEVENT_USAGE_REPORT                    AfEvent = "USAGE_REPORT"
)
