/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ReportAmountMdtAnyOf string

// List of ReportAmountMdtAnyOf
const (
	REPORTAMOUNTMDTANYOF__1       ReportAmountMdtAnyOf = "1"
	REPORTAMOUNTMDTANYOF__2       ReportAmountMdtAnyOf = "2"
	REPORTAMOUNTMDTANYOF__4       ReportAmountMdtAnyOf = "4"
	REPORTAMOUNTMDTANYOF__8       ReportAmountMdtAnyOf = "8"
	REPORTAMOUNTMDTANYOF__16      ReportAmountMdtAnyOf = "16"
	REPORTAMOUNTMDTANYOF__32      ReportAmountMdtAnyOf = "32"
	REPORTAMOUNTMDTANYOF__64      ReportAmountMdtAnyOf = "64"
	REPORTAMOUNTMDTANYOF_INFINITY ReportAmountMdtAnyOf = "infinity"
)
