/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type FlowUsage string

// List of FlowUsage
const (
	FLOWUSAGE_NO_INFO       FlowUsage = "NO_INFO"
	FLOWUSAGE_RTCP          FlowUsage = "RTCP"
	FLOWUSAGE_AF_SIGNALLING FlowUsage = "AF_SIGNALLING"
)
