/*
Nudm_UEAU

UDM UE Authentication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type NodeTypeAnyOf string

// List of NodeTypeAnyOf
const (
	NODETYPEANYOF_AUSF            NodeTypeAnyOf = "AUSF"
	NODETYPEANYOF_VLR             NodeTypeAnyOf = "VLR"
	NODETYPEANYOF_SGSN            NodeTypeAnyOf = "SGSN"
	NODETYPEANYOF_S_CSCF          NodeTypeAnyOf = "S_CSCF"
	NODETYPEANYOF_BSF             NodeTypeAnyOf = "BSF"
	NODETYPEANYOF_GAN_AAA_SERVER  NodeTypeAnyOf = "GAN_AAA_SERVER"
	NODETYPEANYOF_WLAN_AAA_SERVER NodeTypeAnyOf = "WLAN_AAA_SERVER"
	NODETYPEANYOF_MME             NodeTypeAnyOf = "MME"
)
