/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RuleOperation string

// List of RuleOperation
const (
	RULEOPERATION_CREATE_PCC_RULE                               RuleOperation = "CREATE_PCC_RULE"
	RULEOPERATION_DELETE_PCC_RULE                               RuleOperation = "DELETE_PCC_RULE"
	RULEOPERATION_MODIFY_PCC_RULE_AND_ADD_PACKET_FILTERS        RuleOperation = "MODIFY_PCC_RULE_AND_ADD_PACKET_FILTERS"
	RULEOPERATION_MODIFY__PCC_RULE_AND_REPLACE_PACKET_FILTERS   RuleOperation = "MODIFY_ PCC_RULE_AND_REPLACE_PACKET_FILTERS"
	RULEOPERATION_MODIFY__PCC_RULE_AND_DELETE_PACKET_FILTERS    RuleOperation = "MODIFY_ PCC_RULE_AND_DELETE_PACKET_FILTERS"
	RULEOPERATION_MODIFY_PCC_RULE_WITHOUT_MODIFY_PACKET_FILTERS RuleOperation = "MODIFY_PCC_RULE_WITHOUT_MODIFY_PACKET_FILTERS"
)
