/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type AreaEventInfo struct {
	AreaDefinition []ReportingArea `json:"areaDefinition"`

	OccurrenceInfo OccurrenceInfo `json:"occurrenceInfo,omitempty"`

	MinimumInterval int32 `json:"minimumInterval,omitempty"`

	MaximumInterval int32 `json:"maximumInterval,omitempty"`

	SamplingInterval int32 `json:"samplingInterval,omitempty"`

	ReportingDuration int32 `json:"reportingDuration,omitempty"`

	ReportingLocationReq bool `json:"reportingLocationReq,omitempty"`
}
