/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type Model5GVnGroupData struct {
	Dnn string `json:"dnn"`

	SNssai Snssai `json:"sNssai"`

	PduSessionTypes []PduSessionType `json:"pduSessionTypes,omitempty"`

	AppDescriptors []AppDescriptor `json:"appDescriptors,omitempty"`

	SecondaryAuth bool `json:"secondaryAuth,omitempty"`

	DnAaaAddress IpAddress1 `json:"dnAaaAddress,omitempty"`
}
