/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type FailureCause string

// List of FailureCause
const (
	FAILURECAUSE_PCC_RULE_EVENT       FailureCause = "PCC_RULE_EVENT"
	FAILURECAUSE_PCC_QOS_FLOW_EVENT   FailureCause = "PCC_QOS_FLOW_EVENT"
	FAILURECAUSE_RULE_PERMANENT_ERROR FailureCause = "RULE_PERMANENT_ERROR"
	FAILURECAUSE_RULE_TEMPORARY_ERROR FailureCause = "RULE_TEMPORARY_ERROR"
	FAILURECAUSE_POL_DEC_ERROR        FailureCause = "POL_DEC_ERROR"
)
