/*
Nsmf_PDUSession

SMF PDU Session Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RequestIndicationAnyOf string

// List of RequestIndicationAnyOf
const (
	REQUESTINDICATIONANYOF_UE_REQ_PDU_SES_MOD        RequestIndicationAnyOf = "UE_REQ_PDU_SES_MOD"
	REQUESTINDICATIONANYOF_UE_REQ_PDU_SES_REL        RequestIndicationAnyOf = "UE_REQ_PDU_SES_REL"
	REQUESTINDICATIONANYOF_PDU_SES_MOB               RequestIndicationAnyOf = "PDU_SES_MOB"
	REQUESTINDICATIONANYOF_NW_REQ_PDU_SES_AUTH       RequestIndicationAnyOf = "NW_REQ_PDU_SES_AUTH"
	REQUESTINDICATIONANYOF_NW_REQ_PDU_SES_MOD        RequestIndicationAnyOf = "NW_REQ_PDU_SES_MOD"
	REQUESTINDICATIONANYOF_NW_REQ_PDU_SES_REL        RequestIndicationAnyOf = "NW_REQ_PDU_SES_REL"
	REQUESTINDICATIONANYOF_EBI_ASSIGNMENT_REQ        RequestIndicationAnyOf = "EBI_ASSIGNMENT_REQ"
	REQUESTINDICATIONANYOF_REL_DUE_TO_5_G_AN_REQUEST RequestIndicationAnyOf = "REL_DUE_TO_5G_AN_REQUEST"
)
