/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ServAuthInfo string

// List of ServAuthInfo
const (
	SERVAUTHINFO_NOT_KNOWN       ServAuthInfo = "TP_NOT_KNOWN"
	SERVAUTHINFO_EXPIRED         ServAuthInfo = "TP_EXPIRED"
	SERVAUTHINFO_NOT_YET_OCURRED ServAuthInfo = "TP_NOT_YET_OCURRED"
)
