/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RequestPosInfo struct {
	LcsClientType ExternalClientType `json:"lcsClientType"`

	LcsLocation LocationType `json:"lcsLocation"`

	Supi string `json:"supi,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	Priority LcsPriority `json:"priority,omitempty"`

	LcsQoS LocationQoS `json:"lcsQoS,omitempty"`

	VelocityRequested VelocityRequested `json:"velocityRequested,omitempty"`

	LcsSupportedGADShapes SupportedGADShapes `json:"lcsSupportedGADShapes,omitempty"`

	AdditionalLcsSuppGADShapes []SupportedGADShapes `json:"additionalLcsSuppGADShapes,omitempty"`

	LocationNotificationUri string `json:"locationNotificationUri,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	OldGuami Guami `json:"oldGuami,omitempty"`

	Pei string `json:"pei,omitempty"`

	LcsServiceType int32 `json:"lcsServiceType,omitempty"`

	LdrType LdrType `json:"ldrType,omitempty"`

	HgmlcCallBackURI string `json:"hgmlcCallBackURI,omitempty"`

	LdrReference string `json:"ldrReference,omitempty"`

	PeriodicEventInfo PeriodicEventInfo `json:"periodicEventInfo,omitempty"`

	AreaEventInfo AreaEventInfo `json:"areaEventInfo,omitempty"`

	MotionEventInfo MotionEventInfo `json:"motionEventInfo,omitempty"`

	ExternalClientIdentification string `json:"externalClientIdentification,omitempty"`

	AfID string `json:"afID,omitempty"`

	CodeWord string `json:"codeWord,omitempty"`

	UePrivacyRequirements UePrivacyRequirements `json:"uePrivacyRequirements,omitempty"`
}
