/*
Nsmf_PDUSession

SMF PDU Session Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type QosFlowAccessType string

// List of QosFlowAccessTypeAnyOf
const (
	QOSFLOWACCESSTYPEANYOF__3_GPP               QosFlowAccessType = "3GPP"
	QOSFLOWACCESSTYPEANYOF_NON_3_GPP            QosFlowAccessType = "NON_3GPP"
	QOSFLOWACCESSTYPEANYOF__3_GPP_AND_NON_3_GPP QosFlowAccessType = "3GPP_AND_NON_3GPP"
)
