/*
Nsmf_EventExposure

Session Management Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type EventNotification struct {
	Event SmfEvent `json:"event"`

	TimeStamp time.Time `json:"timeStamp"`

	Supi string `json:"supi,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	SourceDnai string `json:"sourceDnai,omitempty"`

	TargetDnai string `json:"targetDnai,omitempty"`

	DnaiChgType DnaiChangeType `json:"dnaiChgType,omitempty"`

	SourceUeIpv4Addr string `json:"sourceUeIpv4Addr,omitempty"`

	SourceUeIpv6Prefix Ipv6Prefix `json:"sourceUeIpv6Prefix,omitempty"`

	TargetUeIpv4Addr string `json:"targetUeIpv4Addr,omitempty"`

	TargetUeIpv6Prefix Ipv6Prefix `json:"targetUeIpv6Prefix,omitempty"`

	SourceTraRouting *RouteToLocation `json:"sourceTraRouting,omitempty"`

	TargetTraRouting *RouteToLocation `json:"targetTraRouting,omitempty"`

	UeMac string `json:"ueMac,omitempty"`

	AdIpv4Addr string `json:"adIpv4Addr,omitempty"`

	AdIpv6Prefix Ipv6Prefix `json:"adIpv6Prefix,omitempty"`

	ReIpv4Addr string `json:"reIpv4Addr,omitempty"`

	ReIpv6Prefix Ipv6Prefix `json:"reIpv6Prefix,omitempty"`

	PlmnId PlmnId `json:"plmnId,omitempty"`

	AccType AccessType `json:"accType,omitempty"`

	PduSeId int32 `json:"pduSeId,omitempty"`

	DddStatus DlDataDeliveryStatus `json:"dddStatus,omitempty"`

	DddTraDescriptor DddTrafficDescriptor `json:"dddTraDescriptor,omitempty"`

	MaxWaitTime time.Time `json:"maxWaitTime,omitempty"`

	CommFailure CommunicationFailure `json:"commFailure,omitempty"`

	Ipv4Addr string `json:"ipv4Addr,omitempty"`

	Ipv6Prefixes []Ipv6Prefix `json:"ipv6Prefixes,omitempty"`

	Ipv6Addrs []Ipv6Addr `json:"ipv6Addrs,omitempty"`

	PduSessType PduSessionType `json:"pduSessType,omitempty"`

	Qfi int32 `json:"qfi,omitempty"`

	AppId string `json:"appId,omitempty"`

	EthfDescs []EthFlowDescription `json:"ethfDescs,omitempty"`

	FDescs []string `json:"fDescs,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`

	UlDelays []int32 `json:"ulDelays,omitempty"`

	DlDelays []int32 `json:"dlDelays,omitempty"`

	RtDelays []int32 `json:"rtDelays,omitempty"`
}
