/*
Nudm_UECM

Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.1.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type DeregistrationReason string

// List of DeregistrationReason
const (
	DEREGISTRATIONREASON_UE_INITIAL_REGISTRATION                       DeregistrationReason = "UE_INITIAL_REGISTRATION"
	DEREGISTRATIONREASON_UE_REGISTRATION_AREA_CHANGE                   DeregistrationReason = "UE_REGISTRATION_AREA_CHANGE"
	DEREGISTRATIONREASON_SUBSCRIPTION_WITHDRAWN                        DeregistrationReason = "SUBSCRIPTION_WITHDRAWN"
	DEREGISTRATIONREASON__5_GS_TO_EPS_MOBILITY                         DeregistrationReason = "5GS_TO_EPS_MOBILITY"
	DEREGISTRATIONREASON__5_GS_TO_EPS_MOBILITY_UE_INITIAL_REGISTRATION DeregistrationReason = "5GS_TO_EPS_MOBILITY_UE_INITIAL_REGISTRATION"
	DEREGISTRATIONREASON_REREGISTRATION_REQUIRED                       DeregistrationReason = "REREGISTRATION_REQUIRED"
	DEREGISTRATIONREASON_SMF_CONTEXT_TRANSFERRED                       DeregistrationReason = "SMF_CONTEXT_TRANSFERRED"
)
