/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ContextDataSetName string

// List of ContextDataSetName
const (
	CONTEXTDATASETNAME_AMF_3_GPP         ContextDataSetName = "AMF_3GPP"
	CONTEXTDATASETNAME_AMF_NON_3_GPP     ContextDataSetName = "AMF_NON_3GPP"
	CONTEXTDATASETNAME_SDM_SUBSCRIPTIONS ContextDataSetName = "SDM_SUBSCRIPTIONS"
	CONTEXTDATASETNAME_EE_SUBSCRIPTIONS  ContextDataSetName = "EE_SUBSCRIPTIONS"
	CONTEXTDATASETNAME_SMSF_3_GPP        ContextDataSetName = "SMSF_3GPP"
	CONTEXTDATASETNAME_SMSF_NON_3_GPP    ContextDataSetName = "SMSF_NON_3GPP"
	CONTEXTDATASETNAME_SUBS_TO_NOTIFY    ContextDataSetName = "SUBS_TO_NOTIFY"
	CONTEXTDATASETNAME_SMF_REG           ContextDataSetName = "SMF_REG"
	CONTEXTDATASETNAME_IP_SM_GW          ContextDataSetName = "IP_SM_GW"
)
