/*
Nsmf_PDUSession

SMF PDU Session Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type NotificationCause string

// List of NotificationCause
const (
	NOTIFICATIONCAUSE_QOS_FULFILLED        NotificationCause = "QOS_FULFILLED"
	NOTIFICATIONCAUSE_QOS_NOT_FULFILLED    NotificationCause = "QOS_NOT_FULFILLED"
	NOTIFICATIONCAUSE_UP_SEC_FULFILLED     NotificationCause = "UP_SEC_FULFILLED"
	NOTIFICATIONCAUSE_UP_SEC_NOT_FULFILLED NotificationCause = "UP_SEC_NOT_FULFILLED"
)
