/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RegistrationContextContainer struct {
	UeContext UeContext `json:"ueContext"`

	LocalTimeZone string `json:"localTimeZone,omitempty"`

	AnType AccessType `json:"anType"`

	AnN2ApId int32 `json:"anN2ApId"`

	RanNodeId GlobalRanNodeId `json:"ranNodeId"`

	InitialAmfName string `json:"initialAmfName"`

	UserLocation UserLocation `json:"userLocation"`

	RrcEstCause string `json:"rrcEstCause,omitempty"`

	UeContextRequest bool `json:"ueContextRequest,omitempty"`

	InitialAmfN2ApId int32 `json:"initialAmfN2ApId,omitempty"`

	AnN2IPv4Addr string `json:"anN2IPv4Addr,omitempty"`

	AnN2IPv6Addr Ipv6Addr `json:"anN2IPv6Addr,omitempty"`

	AllowedNssai AllowedNssai `json:"allowedNssai,omitempty"`

	ConfiguredNssai []ConfiguredSnssai `json:"configuredNssai,omitempty"`

	RejectedNssaiInPlmn []Snssai `json:"rejectedNssaiInPlmn,omitempty"`

	RejectedNssaiInTa []Snssai `json:"rejectedNssaiInTa,omitempty"`

	SelectedPlmnId PlmnId `json:"selectedPlmnId,omitempty"`

	IabNodeInd bool `json:"iabNodeInd,omitempty"`

	CeModeBInd CeModeBInd `json:"ceModeBInd,omitempty"`

	LteMInd LteMInd `json:"lteMInd,omitempty"`

	AuthenticatedInd bool `json:"authenticatedInd,omitempty"`

	NpnAccessInfo NpnAccessInfo `json:"npnAccessInfo,omitempty"`
}
