/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type SmPolicyDeleteData struct {
	UserLocationInfo UserLocation `json:"userLocationInfo,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`

	ServingNetwork PlmnIdNid `json:"servingNetwork,omitempty"`

	UserLocationInfoTime time.Time `json:"userLocationInfoTime,omitempty"`

	// Contains the RAN and/or NAS release cause.
	RanNasRelCauses []RanNasRelCause `json:"ranNasRelCauses,omitempty"`

	// Contains the usage report
	AccuUsageReports []AccuUsageReport `json:"accuUsageReports,omitempty"`

	PduSessRelCause PduSessionRelCause `json:"pduSessRelCause,omitempty"`

	QosMonReports []QosMonitoringReport `json:"qosMonReports,omitempty"`
}
