/*
Npcf_UEPolicyControl

UE Policy Control Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type PolicyAssociationReleaseCauseAnyOf string

// List of PolicyAssociationReleaseCauseAnyOf
const (
	POLICYASSOCIATIONRELEASECAUSEANYOF_UNSPECIFIED PolicyAssociationReleaseCauseAnyOf = "UNSPECIFIED"
	POLICYASSOCIATIONRELEASECAUSEANYOF_UE_SUBSCRIPTION PolicyAssociationReleaseCauseAnyOf = "UE_SUBSCRIPTION"
	POLICYASSOCIATIONRELEASECAUSEANYOF_INSUFFICIENT_RES PolicyAssociationReleaseCauseAnyOf = "INSUFFICIENT_RES"
)
