/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ResponseTime string

// List of ResponseTime
const (
	RESPONSETIME_LOW_DELAY      ResponseTime = "LOW_DELAY"
	RESPONSETIME_DELAY_TOLERANT ResponseTime = "DELAY_TOLERANT"
	RESPONSETIME_NO_DELAY       ResponseTime = "NO_DELAY"
)
