/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

// MediaSubComponent - Identifies a media subcomponent
type MediaSubComponent struct {
	AfSigProtocol AfSigProtocol `json:"afSigProtocol,omitempty"`

	EthfDescs []EthFlowDescription `json:"ethfDescs,omitempty"`

	FNum int32 `json:"fNum"`

	FDescs []string `json:"fDescs,omitempty"`

	FStatus FlowStatus `json:"fStatus,omitempty"`

	MarBwDl string `json:"marBwDl,omitempty"`

	MarBwUl string `json:"marBwUl,omitempty"`

	// 2-octet string, where each octet is encoded in hexadecimal representation. The first octet contains the IPv4 Type-of-Service or the IPv6 Traffic-Class field and the second octet contains the ToS/Traffic Class mask field.
	TosTrCl string `json:"tosTrCl,omitempty"`

	FlowUsage FlowUsage `json:"flowUsage,omitempty"`
}
