/*
Npcf_UEPolicyControl

UE Policy Control Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type PolicyAssociationUpdateRequest struct {
	NotificationUri string `json:"notificationUri,omitempty"`

	// Alternate or backup IPv4 Address(es) where to send Notifications.
	AltNotifIpv4Addrs []string `json:"altNotifIpv4Addrs,omitempty"`

	// Alternate or backup IPv6 Address(es) where to send Notifications.
	AltNotifIpv6Addrs []Ipv6Addr `json:"altNotifIpv6Addrs,omitempty"`

	// Alternate or backup FQDN(s) where to send Notifications.
	AltNotifFqdns []string `json:"altNotifFqdns,omitempty"`

	// Request Triggers that the NF service consumer observes.
	Triggers []RequestTrigger `json:"triggers,omitempty"`

	// Map of PRA status information.
	PraStatuses map[string]PresenceInfo `json:"praStatuses,omitempty"`

	UserLoc UserLocation `json:"userLoc,omitempty"`

	UePolDelResult string `json:"uePolDelResult,omitempty"`

	UePolTransFailNotif UePolicyTransferFailureNotification `json:"uePolTransFailNotif,omitempty"`

	UePolReq string `json:"uePolReq,omitempty"`

	Guami Guami `json:"guami,omitempty"`

	ServingNfId string `json:"servingNfId,omitempty"`

	PlmnId PlmnId `json:"plmnId,omitempty"`

	ConnectState CmState `json:"connectState,omitempty"`

	GroupIds []string `json:"groupIds,omitempty"`
}
