/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type PresenceStateAnyOf string

// List of PresenceStateAnyOf
const (
	PRESENCESTATEANYOF_IN_AREA     PresenceStateAnyOf = "IN_AREA"
	PRESENCESTATEANYOF_OUT_OF_AREA PresenceStateAnyOf = "OUT_OF_AREA"
	PRESENCESTATEANYOF_UNKNOWN     PresenceStateAnyOf = "UNKNOWN"
	PRESENCESTATEANYOF_INACTIVE    PresenceStateAnyOf = "INACTIVE"
)
