/*
Nsmf_PDUSession

SMF PDU Session Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type QosMonitoringReq string

// List of QosMonitoringReq
const (
	QOSMONITORINGREQANYOF_UL   QosMonitoringReq = "UL"
	QOSMONITORINGREQANYOF_DL   QosMonitoringReq = "DL"
	QOSMONITORINGREQANYOF_BOTH QosMonitoringReq = "BOTH"
	QOSMONITORINGREQANYOF_NONE QosMonitoringReq = "NONE"
)
