/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

// AppSessionContext - Represents an Individual Application Session Context resource.
type AppSessionContext struct {
	AscReqData AppSessionContextReqData `json:"ascReqData,omitempty"`

	AscRespData AppSessionContextRespData `json:"ascRespData,omitempty"`

	EvsNotif EventsNotification `json:"evsNotif,omitempty"`
}
