/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ReportIntervalNrMdtAnyOf string

// List of ReportIntervalNrMdtAnyOf
const (
	REPORTINTERVALNRMDTANYOF__120     ReportIntervalNrMdtAnyOf = "120"
	REPORTINTERVALNRMDTANYOF__240     ReportIntervalNrMdtAnyOf = "240"
	REPORTINTERVALNRMDTANYOF__480     ReportIntervalNrMdtAnyOf = "480"
	REPORTINTERVALNRMDTANYOF__640     ReportIntervalNrMdtAnyOf = "640"
	REPORTINTERVALNRMDTANYOF__1024    ReportIntervalNrMdtAnyOf = "1024"
	REPORTINTERVALNRMDTANYOF__2048    ReportIntervalNrMdtAnyOf = "2048"
	REPORTINTERVALNRMDTANYOF__5120    ReportIntervalNrMdtAnyOf = "5120"
	REPORTINTERVALNRMDTANYOF__10240   ReportIntervalNrMdtAnyOf = "10240"
	REPORTINTERVALNRMDTANYOF__20480   ReportIntervalNrMdtAnyOf = "20480"
	REPORTINTERVALNRMDTANYOF__40960   ReportIntervalNrMdtAnyOf = "40960"
	REPORTINTERVALNRMDTANYOF__60000   ReportIntervalNrMdtAnyOf = "60000"
	REPORTINTERVALNRMDTANYOF__360000  ReportIntervalNrMdtAnyOf = "360000"
	REPORTINTERVALNRMDTANYOF__720000  ReportIntervalNrMdtAnyOf = "720000"
	REPORTINTERVALNRMDTANYOF__1800000 ReportIntervalNrMdtAnyOf = "1800000"
	REPORTINTERVALNRMDTANYOF__3600000 ReportIntervalNrMdtAnyOf = "3600000"
)
