/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type NFType string

// List of NFTypeAnyOf
const (
	NFTYPEANYOF_NRF      NFType = "NRF"
	NFTYPEANYOF_UDM      NFType = "UDM"
	NFTYPEANYOF_AMF      NFType = "AMF"
	NFTYPEANYOF_SMF      NFType = "SMF"
	NFTYPEANYOF_AUSF     NFType = "AUSF"
	NFTYPEANYOF_NEF      NFType = "NEF"
	NFTYPEANYOF_PCF      NFType = "PCF"
	NFTYPEANYOF_SMSF     NFType = "SMSF"
	NFTYPEANYOF_NSSF     NFType = "NSSF"
	NFTYPEANYOF_UDR      NFType = "UDR"
	NFTYPEANYOF_LMF      NFType = "LMF"
	NFTYPEANYOF_GMLC     NFType = "GMLC"
	NFTYPEANYOF__5_G_EIR NFType = "5G_EIR"
	NFTYPEANYOF_SEPP     NFType = "SEPP"
	NFTYPEANYOF_UPF      NFType = "UPF"
	NFTYPEANYOF_N3_IWF   NFType = "N3IWF"
	NFTYPEANYOF_AF       NFType = "AF"
	NFTYPEANYOF_UDSF     NFType = "UDSF"
	NFTYPEANYOF_BSF      NFType = "BSF"
	NFTYPEANYOF_CHF      NFType = "CHF"
	NFTYPEANYOF_NWDAF    NFType = "NWDAF"
	NFTYPEANYOF_PCSCF    NFType = "PCSCF"
	NFTYPEANYOF_CBCF     NFType = "CBCF"
	NFTYPEANYOF_HSS      NFType = "HSS"
	NFTYPEANYOF_UCMF     NFType = "UCMF"
	NFTYPEANYOF_SOR_AF   NFType = "SOR_AF"
	NFTYPEANYOF_SPAF     NFType = "SPAF"
	NFTYPEANYOF_MME      NFType = "MME"
	NFTYPEANYOF_SCSAS    NFType = "SCSAS"
	NFTYPEANYOF_SCEF     NFType = "SCEF"
	NFTYPEANYOF_SCP      NFType = "SCP"
	NFTYPEANYOF_NSSAAF   NFType = "NSSAAF"
	NFTYPEANYOF_ICSCF    NFType = "ICSCF"
	NFTYPEANYOF_SCSCF    NFType = "SCSCF"
	NFTYPEANYOF_DRA      NFType = "DRA"
	NFTYPEANYOF_IMS_AS   NFType = "IMS_AS"
	NFTYPEANYOF_CEF      NFType = "CEF"
)
