/*
Nudm_UECM

Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.1.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type DeregistrationReasonAnyOf string

// List of DeregistrationReasonAnyOf
const (
	DEREGISTRATIONREASONANYOF_UE_INITIAL_REGISTRATION                       DeregistrationReasonAnyOf = "UE_INITIAL_REGISTRATION"
	DEREGISTRATIONREASONANYOF_UE_REGISTRATION_AREA_CHANGE                   DeregistrationReasonAnyOf = "UE_REGISTRATION_AREA_CHANGE"
	DEREGISTRATIONREASONANYOF_SUBSCRIPTION_WITHDRAWN                        DeregistrationReasonAnyOf = "SUBSCRIPTION_WITHDRAWN"
	DEREGISTRATIONREASONANYOF__5_GS_TO_EPS_MOBILITY                         DeregistrationReasonAnyOf = "5GS_TO_EPS_MOBILITY"
	DEREGISTRATIONREASONANYOF__5_GS_TO_EPS_MOBILITY_UE_INITIAL_REGISTRATION DeregistrationReasonAnyOf = "5GS_TO_EPS_MOBILITY_UE_INITIAL_REGISTRATION"
	DEREGISTRATIONREASONANYOF_REREGISTRATION_REQUIRED                       DeregistrationReasonAnyOf = "REREGISTRATION_REQUIRED"
	DEREGISTRATIONREASONANYOF_SMF_CONTEXT_TRANSFERRED                       DeregistrationReasonAnyOf = "SMF_CONTEXT_TRANSFERRED"
)
