/*
AUSF API

AUSF UE Authentication Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type AuthenticationInfo struct {

	SupiOrSuci string `json:"supiOrSuci"`

	ServingNetworkName string `json:"servingNetworkName"`

	ResynchronizationInfo ResynchronizationInfo `json:"resynchronizationInfo,omitempty"`

	Pei string `json:"pei,omitempty"`

	TraceData *TraceData `json:"traceData,omitempty"`

	UdmGroupId string `json:"udmGroupId,omitempty"`

	RoutingIndicator string `json:"routingIndicator,omitempty"`

	CellCagInfo []string `json:"cellCagInfo,omitempty"`

	N5gcInd bool `json:"n5gcInd,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`
}
