/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type NonUeN2InfoNotifyRequest struct {
	JsonData N2InformationNotification `json:"jsonData,omitempty"`

	BinaryDataN2Information []byte `json:"binaryDataN2Information,omitempty"`
}
