/*
Nudm_UECM

Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

API version: 1.1.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RegistrationDataSetName string

// List of RegistrationDataSetName
const (
	REGISTRATIONDATASETNAMEANYOF_AMF_3_GPP        RegistrationDataSetName = "AMF_3GPP"
	REGISTRATIONDATASETNAMEANYOF_AMF_NON_3_GPP    RegistrationDataSetName = "AMF_NON_3GPP"
	REGISTRATIONDATASETNAMEANYOF_SMF_PDU_SESSIONS RegistrationDataSetName = "SMF_PDU_SESSIONS"
	REGISTRATIONDATASETNAMEANYOF_SMSF_3_GPP       RegistrationDataSetName = "SMSF_3GPP"
	REGISTRATIONDATASETNAMEANYOF_SMSF_NON_3_GPP   RegistrationDataSetName = "SMSF_NON_3GPP"
)
