/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type MaPduIndication string

// List of MaPduIndication
const (
	MAPDUINDICATION_REQUEST                 MaPduIndication = "MA_PDU_REQUEST"
	MAPDUINDICATION_NETWORK_UPGRADE_ALLOWED MaPduIndication = "MA_PDU_NETWORK_UPGRADE_ALLOWED"
)
