/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type EpsNasIntegrityAlgorithm string

// List of EpsNasIntegrityAlgorithm
const (
	EPSNASINTEGRITYALGORITHM_EIA0 EpsNasIntegrityAlgorithm = "EIA0"
	EPSNASINTEGRITYALGORITHM_EIA1 EpsNasIntegrityAlgorithm = "EIA1"
	EPSNASINTEGRITYALGORITHM_EIA2 EpsNasIntegrityAlgorithm = "EIA2"
	EPSNASINTEGRITYALGORITHM_EIA3 EpsNasIntegrityAlgorithm = "EIA3"
)
