/*
Npcf_EventExposure

PCF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type ReportingInformation struct {
	ImmRep bool `json:"immRep,omitempty"`

	NotifMethod NotificationMethod `json:"notifMethod,omitempty"`

	MaxReportNbr int32 `json:"maxReportNbr,omitempty"`

	MonDur time.Time `json:"monDur,omitempty"`

	RepPeriod int32 `json:"repPeriod,omitempty"`

	SampRatio int32 `json:"sampRatio,omitempty"`

	GrpRepTime int32 `json:"grpRepTime,omitempty"`
}
