/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ContextDataSetNameAnyOf string

// List of ContextDataSetNameAnyOf
const (
	CONTEXTDATASETNAMEANYOF_AMF_3_GPP ContextDataSetNameAnyOf = "AMF_3GPP"
	CONTEXTDATASETNAMEANYOF_AMF_NON_3_GPP ContextDataSetNameAnyOf = "AMF_NON_3GPP"
	CONTEXTDATASETNAMEANYOF_SDM_SUBSCRIPTIONS ContextDataSetNameAnyOf = "SDM_SUBSCRIPTIONS"
	CONTEXTDATASETNAMEANYOF_EE_SUBSCRIPTIONS ContextDataSetNameAnyOf = "EE_SUBSCRIPTIONS"
	CONTEXTDATASETNAMEANYOF_SMSF_3_GPP ContextDataSetNameAnyOf = "SMSF_3GPP"
	CONTEXTDATASETNAMEANYOF_SMSF_NON_3_GPP ContextDataSetNameAnyOf = "SMSF_NON_3GPP"
	CONTEXTDATASETNAMEANYOF_SUBS_TO_NOTIFY ContextDataSetNameAnyOf = "SUBS_TO_NOTIFY"
	CONTEXTDATASETNAMEANYOF_SMF_REG ContextDataSetNameAnyOf = "SMF_REG"
	CONTEXTDATASETNAMEANYOF_IP_SM_GW ContextDataSetNameAnyOf = "IP_SM_GW"
)
