/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ImmediateMdtConf struct {
	JobType JobType `json:"jobType"`

	MeasurementLteList []MeasurementLteForMdt `json:"measurementLteList,omitempty"`

	MeasurementNrList []MeasurementNrForMdt `json:"measurementNrList,omitempty"`

	ReportingTriggerList []ReportingTrigger `json:"reportingTriggerList,omitempty"`

	ReportInterval ReportIntervalMdt `json:"reportInterval,omitempty"`

	ReportIntervalNr ReportIntervalNrMdt `json:"reportIntervalNr,omitempty"`

	ReportAmount ReportAmountMdt `json:"reportAmount,omitempty"`

	EventThresholdRsrp int32 `json:"eventThresholdRsrp,omitempty"`

	EventThresholdRsrq int32 `json:"eventThresholdRsrq,omitempty"`

	EventThresholdRsrpNr int32 `json:"eventThresholdRsrpNr,omitempty"`

	EventThresholdRsrqNr int32 `json:"eventThresholdRsrqNr,omitempty"`

	CollectionPeriodRmmLte CollectionPeriodRmmLteMdt `json:"collectionPeriodRmmLte,omitempty"`

	CollectionPeriodRmmNr CollectionPeriodRmmNrMdt `json:"collectionPeriodRmmNr,omitempty"`

	MeasurementPeriodLte MeasurementPeriodLteMdt `json:"measurementPeriodLte,omitempty"`

	AreaScope AreaScope `json:"areaScope,omitempty"`

	PositioningMethod PositioningMethodMdt `json:"positioningMethod,omitempty"`

	AddPositioningMethodList []PositioningMethodMdt `json:"addPositioningMethodList,omitempty"`

	MdtAllowedPlmnIdList []PlmnId `json:"mdtAllowedPlmnIdList,omitempty"`

	SensorMeasurementList []SensorMeasurement `json:"sensorMeasurementList,omitempty"`
}
