/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ProvidePosInfo struct {
	LocationEstimate GeographicArea `json:"locationEstimate,omitempty"`

	AccuracyFulfilmentIndicator AccuracyFulfilmentIndicator `json:"accuracyFulfilmentIndicator,omitempty"`

	AgeOfLocationEstimate int32 `json:"ageOfLocationEstimate,omitempty"`

	VelocityEstimate VelocityEstimate `json:"velocityEstimate,omitempty"`

	PositioningDataList []PositioningMethodAndUsage `json:"positioningDataList,omitempty"`

	GnssPositioningDataList []GnssPositioningMethodAndUsage `json:"gnssPositioningDataList,omitempty"`

	Ecgi Ecgi `json:"ecgi,omitempty"`

	Ncgi Ncgi `json:"ncgi,omitempty"`

	TargetServingNode string `json:"targetServingNode,omitempty"`

	TargetMmeName string `json:"targetMmeName,omitempty"`

	TargetMmeRealm string `json:"targetMmeRealm,omitempty"`

	UtranSrvccInd bool `json:"utranSrvccInd,omitempty"`

	CivicAddress CivicAddress `json:"civicAddress,omitempty"`

	BarometricPressure int32 `json:"barometricPressure,omitempty"`

	Altitude float64 `json:"altitude,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	ServingLMFIdentification string `json:"servingLMFIdentification,omitempty"`

	LocationPrivacyVerResult LocationPrivacyVerResult `json:"locationPrivacyVerResult,omitempty"`
}
