/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type IntegrityAlgorithmAnyOf string

// List of IntegrityAlgorithmAnyOf
const (
	INTEGRITYALGORITHMANYOF_NIA0 IntegrityAlgorithmAnyOf = "NIA0"
	INTEGRITYALGORITHMANYOF_NIA1 IntegrityAlgorithmAnyOf = "NIA1"
	INTEGRITYALGORITHMANYOF_NIA2 IntegrityAlgorithmAnyOf = "NIA2"
	INTEGRITYALGORITHMANYOF_NIA3 IntegrityAlgorithmAnyOf = "NIA3"
)
