/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type GnssId string

// List of GnssId
const (
	GNSSID_GPS            GnssId = "GPS"
	GNSSID_GALILEO        GnssId = "GALILEO"
	GNSSID_SBAS           GnssId = "SBAS"
	GNSSID_MODERNIZED_GPS GnssId = "MODERNIZED_GPS"
	GNSSID_QZSS           GnssId = "QZSS"
	GNSSID_GLONASS        GnssId = "GLONASS"
	GNSSID_BDS            GnssId = "BDS"
	GNSSID_NAVIC          GnssId = "NAVIC"
)
