/*
Nudm_NIDDAU

Nudm NIDD Authorization Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type NiddAuthUpdateInfo struct {
	AuthorizationData AuthorizationData `json:"authorizationData"`

	InvalidityInd bool `json:"invalidityInd,omitempty"`
}
