/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type AccuUsageReport struct {

	// An id referencing UsageMonitoringData objects associated with this usage report.
	RefUmIds string `json:"refUmIds"`

	// Unsigned integer identifying a volume in units of bytes.
	VolUsage int64 `json:"volUsage,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	VolUsageUplink int64 `json:"volUsageUplink,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	VolUsageDownlink int64 `json:"volUsageDownlink,omitempty"`

	TimeUsage int32 `json:"timeUsage,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	NextVolUsage int64 `json:"nextVolUsage,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	NextVolUsageUplink int64 `json:"nextVolUsageUplink,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	NextVolUsageDownlink int64 `json:"nextVolUsageDownlink,omitempty"`

	NextTimeUsage int32 `json:"nextTimeUsage,omitempty"`
}
