/*
Namf_Location

AMF Location Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type LocationType string

// List of LocationType
const (
	LOCATIONTYPE_CURRENT_LOCATION               LocationType = "CURRENT_LOCATION"
	LOCATIONTYPE_CURRENT_OR_LAST_KNOWN_LOCATION LocationType = "CURRENT_OR_LAST_KNOWN_LOCATION"
	LOCATIONTYPE_NOTIFICATION_VERIFICATION_ONLY LocationType = "NOTIFICATION_VERIFICATION_ONLY"
	LOCATIONTYPE_DEFERRED_LOCATION              LocationType = "DEFERRED_LOCATION"
)
