/*
Nsmf_EventExposure

Session Management Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type AckOfNotify struct {
	NotifId string `json:"notifId"`

	AckResult AfResultInfo `json:"ackResult"`

	Supi string `json:"supi,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`
}
