/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type AccessAndMobilityData struct {
	Location UserLocation `json:"location,omitempty"`

	LocationTs time.Time `json:"locationTs,omitempty"`

	TimeZone string `json:"timeZone,omitempty"`

	TimeZoneTs time.Time `json:"timeZoneTs,omitempty"`

	AccessType AccessType `json:"accessType,omitempty"`

	RegStates []RmInfo `json:"regStates,omitempty"`

	RegStatesTs time.Time `json:"regStatesTs,omitempty"`

	ConnStates []CmInfo `json:"connStates,omitempty"`

	ConnStatesTs time.Time `json:"connStatesTs,omitempty"`

	ReachabilityStatus UeReachability `json:"reachabilityStatus,omitempty"`

	ReachabilityStatusTs time.Time `json:"reachabilityStatusTs,omitempty"`

	SmsOverNasStatus SmsSupport `json:"smsOverNasStatus,omitempty"`

	SmsOverNasStatusTs time.Time `json:"smsOverNasStatusTs,omitempty"`

	// True  The serving PLMN of the UE is different from the HPLMN of the UE; False  The serving PLMN of the UE is the HPLMN of the UE.
	RoamingStatus bool `json:"roamingStatus,omitempty"`

	RoamingStatusTs time.Time `json:"roamingStatusTs,omitempty"`

	CurrentPlmn PlmnId1 `json:"currentPlmn,omitempty"`

	CurrentPlmnTs time.Time `json:"currentPlmnTs,omitempty"`

	RatType []RatType `json:"ratType,omitempty"`

	RatTypesTs time.Time `json:"ratTypesTs,omitempty"`

	SuppFeat string `json:"suppFeat,omitempty"`
}
