/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type LocationAccuracy string

// List of LocationAccuracy
const (
	LOCATIONACCURACY_CELL_LEVEL   LocationAccuracy = "CELL_LEVEL"
	LOCATIONACCURACY_TA_LEVEL     LocationAccuracy = "TA_LEVEL"
	LOCATIONACCURACY_N3_IWF_LEVEL LocationAccuracy = "N3IWF_LEVEL"
	LOCATIONACCURACY_UE_IP        LocationAccuracy = "UE_IP"
	LOCATIONACCURACY_UE_PORT      LocationAccuracy = "UE_PORT"
)
