/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type CreditManagementStatus string

// List of CreditManagementStatus
const (
	CREDITMANAGEMENTSTATUS_END_USER_SER_DENIED CreditManagementStatus = "END_USER_SER_DENIED"
	CREDITMANAGEMENTSTATUS_CREDIT_CTRL_NOT_APP CreditManagementStatus = "CREDIT_CTRL_NOT_APP"
	CREDITMANAGEMENTSTATUS_AUTH_REJECTED       CreditManagementStatus = "AUTH_REJECTED"
	CREDITMANAGEMENTSTATUS_USER_UNKNOWN        CreditManagementStatus = "USER_UNKNOWN"
	CREDITMANAGEMENTSTATUS_RATING_FAILED       CreditManagementStatus = "RATING_FAILED"
)
