/*
Namf_EventExposure

AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type AmfCreatedEventSubscription struct {
	Subscription AmfEventSubscription `json:"subscription"`

	SubscriptionId string `json:"subscriptionId"`

	ReportList []AmfEventReport `json:"reportList,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`
}
