/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

// AfRoutingRequirement - describes the event information delivered in the subscription
type AfRoutingRequirement struct {
	AppReloc bool `json:"appReloc,omitempty"`

	RouteToLocs []RouteToLocation `json:"routeToLocs,omitempty"`

	SpVal SpatialValidity `json:"spVal,omitempty"`

	TempVals []TemporalValidity `json:"tempVals,omitempty"`

	UpPathChgSub *UpPathChgEvent `json:"upPathChgSub,omitempty"`

	AddrPreserInd bool `json:"addrPreserInd,omitempty"`
}
