/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RanNasRelCause struct {
	NgApCause NgApCause `json:"ngApCause,omitempty"`

	Var5gMmCause int32 `json:"5gMmCause,omitempty"`

	Var5gSmCause int32 `json:"5gSmCause,omitempty"`

	// Defines the EPS RAN/NAS release cause.
	EpsCause string `json:"epsCause,omitempty"`
}
