/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type TerminationCause string

// List of TerminationCause
const (
	TERMINATIONCAUSE_ALL_SDF_DEACTIVATION    TerminationCause = "ALL_SDF_DEACTIVATION"
	TERMINATIONCAUSE_PDU_SESSION_TERMINATION TerminationCause = "PDU_SESSION_TERMINATION"
	TERMINATIONCAUSE_PS_TO_CS_HO             TerminationCause = "PS_TO_CS_HO"
)
