/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type SessionRuleFailureCodeAnyOf string

// List of SessionRuleFailureCodeAnyOf
const (
	SESSIONRULEFAILURECODEANYOF_NF_MAL         SessionRuleFailureCodeAnyOf = "NF_MAL"
	SESSIONRULEFAILURECODEANYOF_RES_LIM        SessionRuleFailureCodeAnyOf = "RES_LIM"
	SESSIONRULEFAILURECODEANYOF_UNSUCC_QOS_VAL SessionRuleFailureCodeAnyOf = "UNSUCC_QOS_VAL"
	SESSIONRULEFAILURECODEANYOF_UE_STA_SUSP    SessionRuleFailureCodeAnyOf = "UE_STA_SUSP"
)
