/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type UeContextTransferReqData struct {
	Reason TransferReason `json:"reason"`

	AccessType AccessType `json:"accessType"`

	PlmnId PlmnId `json:"plmnId,omitempty"`

	RegRequest N1MessageContainer `json:"regRequest,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`
}
