/*
Npcf_UEPolicyControl

UE Policy Control Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RequestTrigger string

// List of RequestTrigger
const (
	REQUESTTRIGGER_LOC_CH            RequestTrigger = "LOC_CH"
	REQUESTTRIGGER_PRA_CH            RequestTrigger = "PRA_CH"
	REQUESTTRIGGER_UE_POLICY         RequestTrigger = "UE_POLICY"
	REQUESTTRIGGER_PLMN_CH           RequestTrigger = "PLMN_CH"
	REQUESTTRIGGER_CON_STATE_CH      RequestTrigger = "CON_STATE_CH"
	REQUESTTRIGGER_GROUP_ID_LIST_CHG RequestTrigger = "GROUP_ID_LIST_CHG"
)
