/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type ReportIntervalNrMdt string

// List of ReportIntervalNrMdtAnyOf
const (
	REPORTINTERVALNRMDTANYOF__120     ReportIntervalNrMdt = "120"
	REPORTINTERVALNRMDTANYOF__240     ReportIntervalNrMdt = "240"
	REPORTINTERVALNRMDTANYOF__480     ReportIntervalNrMdt = "480"
	REPORTINTERVALNRMDTANYOF__640     ReportIntervalNrMdt = "640"
	REPORTINTERVALNRMDTANYOF__1024    ReportIntervalNrMdt = "1024"
	REPORTINTERVALNRMDTANYOF__2048    ReportIntervalNrMdt = "2048"
	REPORTINTERVALNRMDTANYOF__5120    ReportIntervalNrMdt = "5120"
	REPORTINTERVALNRMDTANYOF__10240   ReportIntervalNrMdt = "10240"
	REPORTINTERVALNRMDTANYOF__20480   ReportIntervalNrMdt = "20480"
	REPORTINTERVALNRMDTANYOF__40960   ReportIntervalNrMdt = "40960"
	REPORTINTERVALNRMDTANYOF__60000   ReportIntervalNrMdt = "60000"
	REPORTINTERVALNRMDTANYOF__360000  ReportIntervalNrMdt = "360000"
	REPORTINTERVALNRMDTANYOF__720000  ReportIntervalNrMdt = "720000"
	REPORTINTERVALNRMDTANYOF__1800000 ReportIntervalNrMdt = "1800000"
	REPORTINTERVALNRMDTANYOF__3600000 ReportIntervalNrMdt = "3600000"
)
