/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type IptvConfigData struct {
	Supi string `json:"supi,omitempty"`

	InterGroupId string `json:"interGroupId,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`

	AfAppId string `json:"afAppId"`

	MultiAccCtrls map[string]MulticastAccessControl `json:"multiAccCtrls"`

	SuppFeat string `json:"suppFeat,omitempty"`

	ResUri string `json:"resUri,omitempty"`
}
