/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 2.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type SubscriptionDataSubscriptions struct {
	UeId string `json:"ueId,omitempty"`

	CallbackReference string `json:"callbackReference"`

	OriginalCallbackReference string `json:"originalCallbackReference,omitempty"`

	MonitoredResourceUris []string `json:"monitoredResourceUris"`

	Expiry time.Time `json:"expiry,omitempty"`

	SdmSubscription SdmSubscription1 `json:"sdmSubscription,omitempty"`

	SubscriptionId string `json:"subscriptionId,omitempty"`

	UniqueSubscription bool `json:"uniqueSubscription,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`
}
