/*
Namf_EventExposure

AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 1.1.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

import (
	"time"
)

type AmfEventReport struct {
	Type AmfEventType `json:"type"`

	State AmfEventState `json:"state"`

	TimeStamp time.Time `json:"timeStamp"`

	SubscriptionId string `json:"subscriptionId,omitempty"`

	AnyUe bool `json:"anyUe,omitempty"`

	Supi string `json:"supi,omitempty"`

	AreaList []AmfEventArea `json:"areaList,omitempty"`

	RefId int32 `json:"refId,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	Pei string `json:"pei,omitempty"`

	Location UserLocation `json:"location,omitempty"`

	AdditionalLocation UserLocation `json:"additionalLocation,omitempty"`

	Timezone string `json:"timezone,omitempty"`

	AccessTypeList []AccessType `json:"accessTypeList,omitempty"`

	RmInfoList []RmInfo `json:"rmInfoList,omitempty"`

	CmInfoList []CmInfo `json:"cmInfoList,omitempty"`

	Reachability UeReachability `json:"reachability,omitempty"`

	CommFailure CommunicationFailure `json:"commFailure,omitempty"`

	LossOfConnectReason LossOfConnectivityReason `json:"lossOfConnectReason,omitempty"`

	NumberOfUes int32 `json:"numberOfUes,omitempty"`

	Var5gsUserStateList []Model5GsUserStateInfo `json:"5gsUserStateList,omitempty"`

	TypeCode string `json:"typeCode,omitempty"`

	RegistrationNumber int32 `json:"registrationNumber,omitempty"`

	MaxAvailabilityTime time.Time `json:"maxAvailabilityTime,omitempty"`

	UeIdExt []UEIdExt `json:"ueIdExt,omitempty"`

	IdleStatusIndication IdleStatusIndication `json:"idleStatusIndication,omitempty"`
}
