/*
Npcf_SMPolicyControl API

Session Management Policy Control Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.1.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// Templates and customized generator are developed by Quang Tung Thai (tqtung@etri.re.kr)

package models

type RequestedRuleDataTypeAnyOf string

// List of RequestedRuleDataTypeAnyOf
const (
	REQUESTEDRULEDATATYPEANYOF_CH_ID RequestedRuleDataTypeAnyOf = "CH_ID"
	REQUESTEDRULEDATATYPEANYOF_MS_TIME_ZONE RequestedRuleDataTypeAnyOf = "MS_TIME_ZONE"
	REQUESTEDRULEDATATYPEANYOF_USER_LOC_INFO RequestedRuleDataTypeAnyOf = "USER_LOC_INFO"
	REQUESTEDRULEDATATYPEANYOF_RES_RELEASE RequestedRuleDataTypeAnyOf = "RES_RELEASE"
	REQUESTEDRULEDATATYPEANYOF_SUCC_RES_ALLO RequestedRuleDataTypeAnyOf = "SUCC_RES_ALLO"
	REQUESTEDRULEDATATYPEANYOF_EPS_FALLBACK RequestedRuleDataTypeAnyOf = "EPS_FALLBACK"
)
